### ISSUE TITLE
NuGet issue on MonoDevelop/Xamarin Studio (package not found)

### ISSUE THREAD

**Issue by Tak0r** [NancyFx/Nancy.Bootstrappers.StructureMap#41]
Since Unix is actually case sensitive on the folder name it expects the package in the folder "Nancy.Bootstrappers.StructureMap" but since the nupkg file is named "Nancy.Boot**S**trappers.StructureMap" it extracts the package to the directory with upper case "S" in Boot**S**trappers which causes this problem. This is a naming error in the first place and should be fixed at least with the next version! All other Bootstrapper plugins are fine, just this one is not compatible on any platform with case sensitive folder and filenames

**Comment by jvandertil** [comment]
Duplicate of #11, which should probably be reopened now.

**Comment by khellang** [comment]
Are you saying we should go and try to change some of the existing packages or is it enough to just push a new version (possibly also including #39 and #40)?

**Comment by jvandertil** [comment]
I think the issue is with nuget actually, the casing is wrong on the website as well: https://www.nuget.org/packages/Nancy.Bootstrappers.StructureMap

**Comment by Tak0r** [comment]
I wouldn't change existing packages but push the next version with the correct naming (meaning the name should be exactly the same as the package id in the nuspec). This would also be the first package depending on the v4 of structuremap so it's fine I think!

**Comment by jvandertil** [comment]
@Tak0r The issue linked in #11 (https://github.com/Particular/NServiceBus/issues/1271) suggests a deeper problem, but maybe that has been fixed. I'm curious to see if #42 indeed fixed the problem.

**Comment by Tak0r** [comment]
@jvandertil No it's not a deeper problem. It's exactly the same. NuGet Simply extracts the nupkg package and doesen't check the nuspec file for the correct name inside of it. If the nupkg has a different name than the project id inside the nuspec file, we get this behaviour. You might argue that NuGet should check the nuspec inside the nupkg and extract to the directory names after the id, but thats another topic.

**Comment by khellang** [comment]
I'm curious to hear what @yishaigalatz or @maartenba has to say about this? Would if work to just push another package with the changes in #41 or do you have do change something on the server?

**Comment by maartenba** [comment]
If I recall correctly that needs more work (DB and search service data updates). The easy way out here would be to make it "Nancy.BootStrappers.StructureMap" everywhere, with the capital S.

Best reach out to NuGet support if this needs to be changed.

**Comment by Tak0r** [comment]
Since there's still no new release this should be reopened since it's not resolved with the current version of this plugin on top of that it should also update the nancy reference to v1.4.3
